-- Plugins
require("core.options")
require("core.colors")
require("core.keymaps")
--require("plugins.aerial")
require("plugins.heirline")
require("plugins.conform")
require("plugins.autopairs")
require("plugins.blink-cmp")
require("plugins.blink-indent")
require("plugins.fzf")
require("plugins.notify")
require("plugins.gitsigns")
require("plugins.highlight-colors")
require("plugins.lazydev")
require("plugins.lsp-config")
require("plugins.luasnip")
require("plugins.nvim-web-devicons")
require("plugins.oil")
require("plugins.todo")
require("plugins.tsm")
require("plugins.which-key")
require("plugins.nvim-lint")
require("plugins.surround")
require("plugins.yazi")

-- Colorsheme
vim.cmd("colorscheme catppuccin-macchiato")
