vim.opt.mouse = ""
vim.g.autoformat = true
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.mousefocus = true
vim.opt.signcolumn = 'yes'
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.cursorline = true
vim.g.lspconfig_silent = true
vim.opt.winborder = "single"
vim.opt.equalalways = false
vim.opt.timeout = true
vim.opt.timeoutlen = 100
vim.opt.clipboard = "unnamedplus"
vim.opt.laststatus = 3
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true